module.exports = [
    {
        'kind': 100,
        'level': 1,
        'minPlayerCount': 2,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 10,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 0.5, 'preBetCount': 0, 'maxTake': 200}
    },
    {
        'kind': 100,
        'level': 2,
        'minPlayerCount': 3,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 40,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 2, 'preBetCount': 0, 'maxTake': 800}
    },
    {
        'kind': 100,
        'level': 3,
        'minPlayerCount': 3,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 80,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 4, 'preBetCount': 0, 'maxTake': 1600}
    },
    {
        'kind': 100,
        'level': 4,
        'minPlayerCount': 3,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 200,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 10, 'preBetCount': 0, 'maxTake': 4000}
    },
    {
        'kind': 100,
        'level': 5,
        'minPlayerCount': 3,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 20,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 0.5, 'preBetCount': 5, 'maxTake': 200}
    },
    {
        'kind': 100,
        'level': 6,
        'minPlayerCount': 3,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 80,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 2, 'preBetCount': 20, 'maxTake': 800}
    },
    {
        'kind': 100,
        'level': 7,
        'minPlayerCount': 3,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 160,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 4, 'preBetCount': 40, 'maxTake': 1600}
    },
    {
        'kind': 100,
        'level': 8,
        'minPlayerCount': 3,
        'maxPlayerCount': 9,
        'baseScore': 1,
        'goldLowerLimit': 400,
        'goldUpper': 0,
        'matchRoom': 1,
        'maxDrawCount': 1,
        'minRobotCount': 2,
        'maxRobotCount': 7,
        'parameters': {'blindBetCount': 10, 'preBetCount': 100, 'maxTake': 4000}
    },
]
